### ISSUE TITLE
CSS files missing

### ISSUE THREAD

**Issue by jurriaan** [t13a/gitit-bootstrap-theme#1]
After installing this theme fontawesome and syntax highlighting doesn't work.

Looks like some CSS files are missing:

I get 404's on:

- `fontawesome.css`
- `solid.css`
- `hk-pyg.css`

Maybe something's missing in the build script?

**Comment by t13a** [comment]
@jurriaan Thanks for repoting! I will investigate from now.

Can you tell me which version of Gitit you are using?

**Comment by jurriaan** [comment]
I'm using the latest version, v0.12.3.1

**Comment by t13a** [comment]
Fix completed. The cause of the problem was due to my weird mistake and upstream updates. With this fix, we've officially supported to v0.12.3.1.

I also have a [theme-applied Docker container](https://hub.docker.com/r/t13a/gitit-experimental), so you can try it out if you are using Docker.
